# Salt.Box config is autogenerated for the container and should not be edit.

# Redis conf:
REDIS_HOST='redis-salt'
REDIS_USERNAME='${REDIS_USERNAME}'
REDIS_PASSWORD='${REDIS_PASSWORD}'
REDIS_SSL_USE=True
REDIS_SSL_CA_CERTS='/etc/redis/certs/ca.crt'

# Salt.box bridge conf:
# Time to live for job returns and grains (sec)
EXPIRE=604800

GITFS_SERVER=sshfs
GITFS_PORT=1022
GITFS_PRIVKEY='/var/lib/saltbox-bridge/ssh/saltbox_ed25519'
GITFS_PUBKEY='/var/lib/saltbox-bridge/ssh/saltbox_ed25519.pub'

SSHFS_SYNC_ON=False
