---

variables:
  CONFIG_FILE_PATH: './saltbox_bridge/pyproject.toml'

stages:
  - test
  - bump-version
  - build


include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'

  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'

  - project: 'saltbox/ci-lib'
    file: 'set-version.yml'


.lint-job:
  stage: test
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
  image: python:3.10-alpine
  before_script:
    - mkdir -p "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install -e ./saltbox_bridge[dev,salt]
    - python -V
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


Ruff:
  extends: .lint-job
  script: 'ruff check saltbox_bridge --config $CONFIG_FILE_PATH'


Mypy:
  extends: .lint-job
  script: 'mypy saltbox_bridge --config-file $CONFIG_FILE_PATH'


Bump Salt Master version:
  stage: bump-version
  extends: .set-backend-version
  variables:
    INNER_VERSION_FILE: 'saltbox_bridge/saltbox_bridge/__init__.py'


Build Salt Master image:
  stage: build
  extends: .build-image
  variables:
    TARGET: salt-master
    REGISTRY_ADDITIONAL_PATH: '/salt-master'
