name: CI


on:
  pull_request


env:
  CONFIG_FILE_PATH: './saltbox_bridge/pyproject.toml'


jobs:
  export-pr-number:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.number }}" > pr_number.txt
      - uses: actions/upload-artifact@v7
        with:
          name: pr-number
          path: pr_number.txt


  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -e ./saltbox_bridge[dev,salt]
      - run: ruff check saltbox_bridge --config ${CONFIG_FILE_PATH}


  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -e ./saltbox_bridge[dev,salt]
      - run: mypy saltbox_bridge --config-file ${CONFIG_FILE_PATH}
